### ISSUE TITLE
Wallet Restore

### ISSUE THREAD

**Issue by hejhog** [Litecash-Dev/litecash#2]
Created Wallet
Transferred 0.999999 (1 CASH - fee) to Wallet.
Balance shows correctly once synced.
Renamed wallet.db to wallet.dbOriginal
Restored Wallet from seed.
Balance shows 0 CASH ...

Therefore Transferred 0.99999900 (1 CASH - fee) to the restored wallet.
Balance shows correctly once synced.
Tried Restoring Wallet again from seed.  Shows 0 CASH.

Tried restore a 3rd time.  Same result.  I now have 3 wallets with 0.999999 CASH!!!!!

Is there an issue with seed restore?

[beam v2.5.96 ubuntu report.zip](https://github.com/Litecash-Dev/litecash/files/8577750/beam.v2.5.96.ubuntu.report.zip)

**Comment by TheNerd** [comment]
If I understand correctly, you are restoring to the same pc right? If you close the wallet, copy the original wallet.db file back to where it was, and then re-open the wallet, does it show the right balance now?

**Comment by hejhog** [comment]
Same PC.  Original Wallet only shows the one transaction of 0.999999 - Blockchain Height is showing as 1789892

**Comment by TheNerd** [comment]
That looks correct. Are you set up to use a remote node or local node?

**Comment by hejhog** [comment]
Remote Node: explorer.lite-cash.com:10000

**Comment by TheNerd** [comment]
Ok try changing it to localnode and make sure to have a peer in the list. 

You can use the same explore address you are using for remote node. You can also add ca1.lite-cash.com:10000. It's good to have more than one.

**Comment by TheNerd** [comment]
Any luck?

**Comment by hejhog** [comment]
Perfect.  Balance now 2.999997.
Just to confirm. Running on local nodes explorer.lite-cash.com:10000 and ca1.lite-cash.com:10000

**Comment by TheNerd** [comment]
yep that should work just fine :)
