### ISSUE TITLE
GUI wallet - bad link on settings page

### ISSUE THREAD

**Issue by TheNerd** [Litecash-Dev/litecash#6]
The link to the Telegram channel on the settings page points to https://t.me/litecashtechnology which is a channel that no longer exists. It should probably be pointed to the main channel as that one is where mostly everyone is. 

https://t.me/litecashgroup is the correct link. 

![image](https://github.com/Litecash-Dev/litecash/assets/445276/e2f96828-975b-4c30-8d27-b20474a15895)

**Comment by TheNerd** [comment]
Well that was dumb. This is what @Maxnflaxl just fixed. Reading is hard sometimes.

**Comment by Maxnflaxl** [comment]
hehe
